// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwaxosyqgkucnowsayeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3YXhvc3lxZ2t1Y25vd3NheWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTc1ODIsImV4cCI6MjA2OTI5MzU4Mn0.y7s5f8KCFbM0jIBD-zGyaj39zi3PaEE3Yiqkn6DYj14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});